# Generated by Django 5.0.7 on 2024-07-18 12:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MSG',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-update', '-create']},
        ),
    ]
